sdn_controller:
  base_url: "http://10.9.69.248:8080"
  endpoints:
    switches: "/v1.0/topology/switches"
    hosts: "/v1.0/topology/hosts"
    links: "/v1.0/topology/links"
  poll_interval_seconds: 5

kafka:
  bootstrap_servers: "localhost:9092"
  topics:
    switches: "topology_switches"
    hosts: "topology_hosts"
    links: "topology_links"

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "*******" # Updated password
  database: "neo4j"
